### ISSUE TITLE
[REQ]

### ISSUE THREAD

**Issue by Kagebe** [dfherr/ThreatClassic2#42] opened 2020-04-15 18:50 UTC
### What is the feature you would like requested?
Hey at first thank you for your work. Your Addon is my first choice Threat Addon.
A friend of mine has recently started using Black Amnesty (https://classic.wowhead.com/item=19166/black-amnesty). We have determined that the aggro reduction is not registered by the threat meter.
Is there a way for you to integrate the procs of this item?
Thank you and greetings from Germany!

**Comment by dfherr** [comment] 2020-04-21 12:19
duplicate of https://github.com/dfherr/ThreatClassic2/issues/32

However, I can't add this without having combat log entries (the ones in `Logs/WoWCombatLog.txt`) showing how the weapon works. Is it a buff, spell cast, debuff?

**Closed by dfherr** 2020-04-21 12:19 UTC
Labels: enhancement
